Repository ISISComputingGroup/ibex_utils, pull requests merged in 2020-04, with the labels that each got.

#66 Retry delete
  installation_and_upgrade/ibex_install_utils/file_utils.py
Labels: size/S

#60 Ticket5176
  installation_and_upgrade/ibex_install_utils/admin_runner.py
  installation_and_upgrade/ibex_install_utils/file_utils.py
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/M

#67 Ticket4776 fix alarm database
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/XS

#68 Ticket5327 mysql error stop
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/XS
