Repository ISISComputingGroup/ibex_utils, pull requests merged in 2020-10, with the labels that each got.

#90 Ticket5639 galil ini parser
  .gitignore
  galil_ini_parser/change_home_conventions.py
  galil_ini_parser/galil_ini_parser.py
  galil_ini_parser/parser_tests.py
Labels: size/XL

#91 Use decode to convert bytes to unicode
  installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
Labels: size/XS

#93 Add RhFe sensor converter
  workflow_support_scripts/convert_temp_calib_files.py
  workflow_support_scripts/opi_diff.bat
Labels: size/M
