Repository ISISComputingGroup/ibex_utils, pull requests merged in 2020-01, with the labels that each got.

#48 Ticket4841 install genie python 3
  installation_and_upgrade/IBEX_upgrade.py
  installation_and_upgrade/define_latest_genie_python.bat
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/L

#49 Fix install
  installation_and_upgrade/IBEX_upgrade.py
  installation_and_upgrade/ibex_install_utils/exceptions.py
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/XS

#51 Install latest mysql
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/M

#52 Update install tasks
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/XS

#50 Add instructions for configuring IE.
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/S
