Repository ISISComputingGroup/ibex_utils, pull requests merged in 2020-06, with the labels that each got.

#74 Purge old script_generator builds
  build_tools/purge_archive.py
Labels: size/XS

#75 Add PYTHONUNBUFFERED
  installation_and_upgrade/instrument_install_latest_build_only.bat
Labels: size/XS

#76 Add purge of symbols
  build_tools/purge_archive.bat
Labels: size/S

#70 Ticket4415 vhd build
  installation_and_upgrade/Jenkinsfile_vhd_creation
  installation_and_upgrade/ibex_install_utils/admin_runner.py
  installation_and_upgrade/ibex_install_utils/ca_utils.py
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/run_process.py
  installation_and_upgrade/ibex_install_utils/tasks/__init__.py
  installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/client_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/common_paths.py
  installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/python_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
  installation_and_upgrade/ibex_install_utils/user_prompt.py
  installation_and_upgrade/vhd_build.bat
  installation_and_upgrade/vhd_scheduled_task.bat
  installation_and_upgrade/vhd_scheduled_task.py
Labels: size/XXL

#78 Use admin. Automate ISISICP patch.
  installation_and_upgrade/IBEX_upgrade.py
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/python_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/M
