Repository ISISComputingGroup/ibex_utils, pull requests merged in 2020-11, with the labels that each got.

#94 Added task for installing shared scripts repo
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/M

#96 Fix create vhd
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
Labels: size/S

#97 Fix VHD build: round 2
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
  installation_and_upgrade/vhd_scheduled_task.py
Labels: size/XS

#98 Fix VHD build: round 3
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
Labels: size/S

#100 Remove muonfe isisicp patch
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/S

#101 Fix install python check
  installation_and_upgrade/define_latest_genie_python.bat
  installation_and_upgrade/instrument_deploy.bat
  installation_and_upgrade/instrument_install.bat
  installation_and_upgrade/instrument_install_latest_build_only.bat
  installation_and_upgrade/instrument_update.bat
Labels: size/S
