Repository ISISComputingGroup/ibex_utils, pull requests merged in 2020-03, with the labels that each got.

#58 added new developer script
  installation_and_upgrade/developer_update.bat
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/M

#59 Added step to update script definitions
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/XS

#62 Use local python
  installation_and_upgrade/instrument_deploy.bat
Labels: size/XS

#64 Use /MT for delete
  installation_and_upgrade/ibex_install_utils/file_utils.py
Labels: size/XS

#57 Add upgrade step to change user shortcuts
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/S

#65 Fix auto install
  installation_and_upgrade/ibex_install_utils/ca_utils.py
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/XS

#61 added popd to exit working directory set by pushd.
  build_tools/purge_archive.bat
  installation_and_upgrade/define_latest_genie_python.bat
  installation_and_upgrade/developer_update.bat
  installation_and_upgrade/instrument_deploy.bat
  installation_and_upgrade/instrument_install_latest_build_only.bat
  installation_and_upgrade/truncate_database.bat
  installation_and_upgrade/upgrade_mysql.bat
Labels: size/XS

#63 Ticket 5164: Added explicit check for MUONFE fix
  installation_and_upgrade/ibex_install_utils/install_tasks.py
Labels: size/XS
