Repository ISISComputingGroup/ibex_utils, pull requests merged in 2022-08, with the labels that each got.

#127 Update IBEX_upgrade.py
  installation_and_upgrade/IBEX_upgrade.py
Labels: size/XS

#129 Add save settings script
  installation_and_upgrade/instrument_save_settings.bat
Labels: size/S

#128 Refactor Check Build Stability Script
  developer_support_script/check_build_stability.py
Labels: size/L

#130 Ticket7250 fix partial release install
  installation_and_upgrade/IBEX_upgrade.py
Labels: size/M
