Repository ISISComputingGroup/ibex_utils, pull requests merged in 2022-11, with the labels that each got.

#132 Ticket7384
  installation_and_upgrade/IBEX_upgrade.py
Labels: size/S

#137 Ticket7454
  installation_and_upgrade/IBEX_upgrade.py
  installation_and_upgrade/ibex_install_utils/file_utils.py
  installation_and_upgrade/ibex_install_utils/logger.py
  installation_and_upgrade/ibex_install_utils/run_process.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/L

#140 Add missing 'f' to strings
  installation_and_upgrade/ibex_install_utils/file_utils.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/XS

#141 makedirs
  installation_and_upgrade/ibex_install_utils/logger.py
Labels: size/XS

#142 Don't log to var area for VHD builds
  installation_and_upgrade/IBEX_upgrade.py
  installation_and_upgrade/vhd_build.bat
  installation_and_upgrade/vhd_build_force_cleanup.bat
  installation_and_upgrade/vhd_build_release.bat
Labels: size/S
