Repository ISISComputingGroup/ibex_utils, pull requests merged in 2022-10, with the labels that each got.

#133 Updated IOC copier to allow creation of IOC 2
  ioc_copier/ioc_copier.py
  ioc_copier/test_ioc_copier.py
Labels: size/L

#134 Run git update as admin if needed
  installation_and_upgrade/ibex_install_utils/admin_runner.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/S

#136 Ticket7441
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/XS

#135 Ticket7431
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/S
