Repository ISISComputingGroup/ibex_utils, pull requests merged in 2023-06, with the labels that each got.

#157 added admin check to bat file
  installation_and_upgrade/instrument_deploy.bat
Labels: size/XS

#159 Ticket6973
  release_scripts/Jenkinsfile_branches
  release_scripts/branches.py
  release_scripts/requirements.txt
Labels: size/L

#161 Ticket7841
  developer_support_script/check_build_stability.py
Labels: size/L

#162 Fixed stability check Failing when build failure with no test report
  developer_support_script/check_build_stability.py
Labels: size/M

#158 Checks that the backup files have been created successfully by looking for specific sentinel files (VERSION.txt)
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
Labels: size/M
