Repository ISISComputingGroup/ibex_utils, pull requests merged in 2024-01, with the labels that each got.

#173 Add parse_rules and post build action to Jenkins job
  build_tools/JenkinsfileCheckRecentBuilds
  build_tools/parse_rules
Labels: size/S

#174 Change parse rules and disable unstableOnWarning
  build_tools/JenkinsfileCheckRecentBuilds
  build_tools/parse_rules
Labels: size/XS

#175 gc and prune if error
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/S

#172 Add step to remove inst script hook
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/python_tasks.py
Labels: size/S

#176 Ticket8186_ignore_list_not_passed_to_move_func
  installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
Labels: size/M

#178 Update motor_params.py
  installation_and_upgrade/ibex_install_utils/motor_params.py
Labels: size/XS

#179 Update java versions
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/XS

#180 Ignore some dirs in backup
  installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
Labels: size/S

#182 Merged counting of files and getting dir size
  installation_and_upgrade/ibex_install_utils/file_utils.py
  installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
Labels: size/M

#181 adding instconfigs url and using in config pushing check
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/XS

#183 Use long paths
  installation_and_upgrade/ibex_install_utils/file_utils.py
  installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
Labels: size/M

#184 Fix git path issue
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/XS

#177 Print guidance if share does not exist
  installation_and_upgrade/instrument_deploy.bat
Labels: size/S
