Repository ISISComputingGroup/ibex_utils, pull requests merged in 2024-11, with the labels that each got.

#211 add standalone isisicp installer
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/update_icp.bat
Labels: size/S

#212 Fixes define genie python
  installation_and_upgrade/define_latest_genie_python.bat
Labels: size/XS

#213 Adjust release-creation scripts to refer to uktena repo for python distribution creation
  release_scripts/Jenkinsfile_branches
  release_scripts/branches.py
Labels: size/M
