Repository ISISComputingGroup/ibex_utils, pull requests merged in 2024-10, with the labels that each got.

#207 Update MySQL
  installation_and_upgrade/ibex_install_utils/admin_runner.py
  installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
Labels: size/M

#205 8437 create network independent python venv
  build_tools/check_builds_are_recent.bat
  build_tools/purge_archive.bat
  installation_and_upgrade/define_latest_genie_python.bat
  installation_and_upgrade/developer_update.bat
  installation_and_upgrade/instrument_deploy.bat
  installation_and_upgrade/instrument_install.bat
  installation_and_upgrade/instrument_install_latest_build_only.bat
  installation_and_upgrade/instrument_save_settings.bat
  installation_and_upgrade/instrument_test.bat
  installation_and_upgrade/instrument_update.bat
  installation_and_upgrade/remove_genie_python.bat
  installation_and_upgrade/run_standalone_backup.bat
  installation_and_upgrade/save_motor_params.bat
  installation_and_upgrade/truncate_database.bat
  installation_and_upgrade/upgrade_mysql.bat
  installation_and_upgrade/vhd_build.bat
  installation_and_upgrade/vhd_build_force_cleanup.bat
  installation_and_upgrade/vhd_build_release.bat
Labels: size/L

#208 Fixes genie python install variables
  installation_and_upgrade/define_latest_genie_python.bat
  installation_and_upgrade/remove_genie_python.bat
Labels: size/M

#210 Use remove function in case directory missing
  installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
Labels: size/XS

#209 Tidy ups and extra error checking
  build_tools/check_builds_are_recent.bat
  build_tools/purge_archive.bat
  installation_and_upgrade/define_latest_genie_python.bat
  installation_and_upgrade/developer_update.bat
  installation_and_upgrade/instrument_install.bat
  installation_and_upgrade/instrument_save_settings.bat
  installation_and_upgrade/instrument_test.bat
  installation_and_upgrade/instrument_update.bat
  installation_and_upgrade/remove_genie_python.bat
  installation_and_upgrade/run_standalone_backup.bat
  installation_and_upgrade/truncate_database.bat
  installation_and_upgrade/upgrade_mysql.bat
  installation_and_upgrade/vhd_build.bat
  installation_and_upgrade/vhd_build_force_cleanup.bat
  installation_and_upgrade/vhd_build_release.bat
Labels: size/M
