Repository ISISComputingGroup/ibex_utils, pull requests merged in 2025-08, with the labels that each got.

#267 Default `expected_return_code` to `[0]`
  installation_and_upgrade/ibex_install_utils/run_process.py
  installation_and_upgrade/truncate_database.bat
Labels: size/XS

#274 update link, recognise we are deploying two versions at a time now
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/XS

#276 headlessly install java
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/XS

#273 Delete release_scripts/Jenkinsfile_branches - now done in github actions
  release_scripts/Jenkinsfile_branches
Labels: size/L

#269 Remove restart VIs step
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/S
