Repository ISISComputingGroup/ibex_utils, pull requests merged in 2025-05, with the labels that each got.

#236 Purge win11 client build
  build_tools/purge_archive.py
Labels: size/XS

#237 Error if both galil drivers appear enabled
  installation_and_upgrade/instrument_deploy.bat
  installation_and_upgrade/instrument_install_latest_build_only.bat
Labels: size/M

#232 Ticket 8597
  installation_and_upgrade/ibex_install_utils/admin_runner.py
  installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
Labels: size/M

#238 Delete build branches directories
  build_tools/purge_archive.bat
Labels: size/S

#239 Add NUL
  build_tools/purge_archive.bat
Labels: size/XS

#240 Use rd instead of del
  build_tools/purge_archive.bat
Labels: size/XS
