Repository ISISComputingGroup/ibex_utils, pull requests merged in 2025-01, with the labels that each got.

#218 genie uninstall: Kill caRepeater if running
  installation_and_upgrade/remove_genie_python.bat
Labels: size/XS

#217 Update genie modules on non-release install (primarily for system tests)
  installation_and_upgrade/instrument_install_latest_build_only.bat
  installation_and_upgrade/update_genie_python_module.bat
Labels: size/S

#219 Set upstream on all local branches
  installation_and_upgrade/ibex_install_utils/tasks/git_tasks.py
Labels: size/S

#220 Add backup move script
  installation_and_upgrade/move_old_ibex_backups.bat
Labels: size/XS

#221 move old backups first
  installation_and_upgrade/ibex_install_utils/tasks/backup_tasks.py
Labels: size/M

#222 Setup python explicitly
  .github/workflows/push_event_workflow.yml
Labels: size/XS

#223 simplify hotfix options
  installation_and_upgrade/IBEX_upgrade.py
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/mysql_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/L

#224 Start server in new env
  installation_and_upgrade/instrument_deploy.bat
Labels: size/XS

#225 Capture logrotate task output
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
Labels: size/XS
