Repository ISISComputingGroup/ibex_utils, pull requests merged in 2025-09, with the labels that each got.

#280 Update check_build_stability.py
  developer_support_script/check_build_stability.py
Labels: size/XS

#277 install rust
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
  installation_and_upgrade/requirements.txt
Labels: size/S

#279 remove seci and treesize prompts
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
Labels: size/M
