Repository ISISComputingGroup/ibex_utils, pull requests merged in 2025-07, with the labels that each got.

#246 Update JenkinsfileCheckRecentBuilds
  build_tools/JenkinsfileCheckRecentBuilds
Labels: size/S

#248 Try uv
  .github/workflows/Linter.yml
  installation_and_upgrade/calibration_files_updater.py
  installation_and_upgrade/define_latest_genie_python.bat
  installation_and_upgrade/developer_update.bat
  installation_and_upgrade/ibex_install_utils/ca_utils.py
  installation_and_upgrade/ibex_install_utils/install_tasks.py
  installation_and_upgrade/ibex_install_utils/motor_params.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/system_tasks.py
  installation_and_upgrade/install_or_update_uv.bat
  installation_and_upgrade/instrument_deploy.bat
  installation_and_upgrade/instrument_install.bat
  installation_and_upgrade/instrument_install_latest_build_only.bat
  installation_and_upgrade/instrument_save_settings.bat
  installation_and_upgrade/instrument_test.bat
  installation_and_upgrade/remove_genie_python.bat
  installation_and_upgrade/requirements.txt
  installation_and_upgrade/run_standalone_backup.bat
  installation_and_upgrade/run_tests.bat
  installation_and_upgrade/save_motor_params.bat
  installation_and_upgrade/set_epics_ca_addr_list.bat
  installation_and_upgrade/set_up_venv.bat
  installation_and_upgrade/truncate_database.bat
  installation_and_upgrade/update_icp.bat
  installation_and_upgrade/upgrade_mysql.bat
  installation_and_upgrade/vhd_build.bat
  installation_and_upgrade/vhd_build_force_cleanup.bat
  installation_and_upgrade/vhd_build_release.bat
Labels: size/XL

#249 fix the build by putting kits_icp_path back in where needed
  installation_and_upgrade/instrument_install_latest_build_only.bat
  installation_and_upgrade/vhd_build.bat
  installation_and_upgrade/vhd_build_force_cleanup.bat
Labels: size/XS

#251 Uv
  installation_and_upgrade/install_or_update_uv.bat
Labels: size/XS

#252 Fixes for new jenkins build names
  installation_and_upgrade/IBEX_upgrade.py
  installation_and_upgrade/ibex_install_utils/tasks/server_tasks.py
  installation_and_upgrade/ibex_install_utils/tasks/vhd_tasks.py
  installation_and_upgrade/instrument_install_latest_build_only.bat
Labels: size/M

#253 Use uv more
  build_tools/check_builds_are_recent.bat
  build_tools/purge_archive.bat
Labels: size/S

#254 Use xcopy
  installation_and_upgrade/install_or_update_uv.bat
Labels: size/XS

#256 Update JenkinsfileCheckRecentBuilds
  build_tools/JenkinsfileCheckRecentBuilds
Labels: size/XS

#261 store pat
  .github/workflows/create-release-branches.yml
Labels: size/XS
